# docker build -f Dockerfile.cron -t gcr.io/cmpt-756-serverful/demo/currency-cron . && docker push gcr.io/cmpt-756-serverful/demo/currency-cron

FROM python:3.10.8-slim@sha256:49749648f4426b31b20fca55ad854caa55ff59dc604f2f76b57d814e0a47c181

WORKDIR /currency_cron

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY cron.py .

ENTRYPOINT ["python", "cron.py"]
